;
;                      /^--^\     /^--^\     /^--^\
;                      \____/     \____/     \____/
;                     /      \   /      \   /      \
;                    |        | |        | |        |
;                     \__  __/   \__  __/   \__  __/
;|^|^|^|^|^|^|^|^|^|^|^|^\ \^|^|^|^/ /^|^|^|^|^\ \^|^|^|^|^|^|^|^|^|^|^|^|
;| | | | | | | | | | | | |\ \| | |/ /| | | | | | \ \ | | | | | | | | | | |
;| | | | | | | | | | | | / / | | |\ \| | | | | |/ /| | | | | | | | | | | |
;| | | | | | | | | | | | \/| | | | \/| | | | | |\/ | | | | | | | | | | | |
;#########################################################################
;| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
;| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |



[colors]
;; Main colors
background = #282a36
foreground = #f8f8f2
sep = #9494b8

; Default colors
white = #FFFFFF
black = #000000
red = #ff5555
pink = #ff79c6
purple = #bd93f9
cyan = #8be9fd
teal = #00B19F
green = #50fa7b
yellow = #f1fa8c
orange = #ffb86c
comment = #6272a4
lightpurple = #ddcbf7
current = #44475a

