
;                      /^--^\     /^--^\     /^--^\
;                      \____/     \____/     \____/
;                     /      \   /      \   /      \
;                    |        | |        | |        |
;                     \__  __/   \__  __/   \__  __/
;|^|^|^|^|^|^|^|^|^|^|^|^\ \^|^|^|^/ /^|^|^|^|^\ \^|^|^|^|^|^|^|^|^|^|^|^|
;| | | | | | | | | | | | |\ \| | |/ /| | | | | | \ \ | | | | | | | | | | |
;| | | | | | | | | | | | / / | | |\ \| | | | | |/ /| | | | | | | | | | | |
;| | | | | | | | | | | | \/| | | | \/| | | | | |\/ | | | | | | | | | | | |
;#########################################################################
;| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |
;| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |


[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL top value
; Used for top aligned bars
margin-bottom = 0

; Adjust the _NET_WM_STRUT_PARTIAL bottom value
; Used for bottom aligned bars
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; File Inclusion
; include an external file, like module file, etc.


include-file = ~/.config/polybar/purple/colors.ini 



[bar/main]

width = 100%
height = 24
radius = 0.0
separator =  
background = ${colors.background}
foreground = ${colors.foreground}
padding-left = 3pt 
padding-right = 3pt
padding = 0
module-margin-left = 0
module-margin-right = 0
;----------------------------------------------------------
; Definição de Fontes
font-0 = "JetBrainsMono Nerd Font:size=10;2"
font-1 = "JetBrainsMono Nerd Font:size=18;2"
font-2 =  "CaskaydiaCoveNerdFontMono-Regular:size=12;2"
font-3 = "JetBrainsMono Nerd Font:antialias=false:size=22;5.1"
font-4 = "JetBrainsMono Nerd Font:size=1;1"
font-5 = "JetBrainsMono Nerd Font:size=14;3"
font-6 = "JetBrainsMono Nerd Font:size=8;1.5"
font-7 = "CaskaydiaCoveNerdFontMono-Regular:size=13;4"
;------------------------------------------------

; Definição de Modulos
modules-left = sysmenu sep xworkspaces sep cpu_icon cpu_bar sep cpu_temperature_icon cpu_temperature  sep memory_icon memory sep filesystem_icon sep filesystem
modules-center = time_icon time sep date_icon date sep
modules-right = mpd sep volume sep wired-network



[bar]
fill = ⏽
empty = ⏽
separator = 
indicator =
[module/volume]

type = internal/alsa

; Available controls:
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default
master-mixer = Master

; Increasing volume in Percent
interval = 1


; How it is show in the bar 
; Example: 
; 50% 󰖀 ⏽⏽⏽⏽⏽⏽⏽⏽⏽⏽⏽
format-volume = <label-volume> <ramp-volume> <bar-volume>

format-muted = <label-muted>
format-muted-prefix = 󰝟
format-muted-prefix-font = 1
format-muted-prefix-foreground = ${colors.yellow} 

; Variables 
label-volume = %percentage%%
label-volume-foreground = ${colors.purple}


label-muted = " Sem som"
label-muted-foreground = ${colors.foreground}
label-muted-font = 1

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.purple}

bar-volume-format = "%fill%%indicator%%empty%"
bar-volume-width = 11
bar-volume-gradient = false

bar-volume-indicator = ${bar.indicator}
bar-volume-indicator-foreground = ${colors.purple}
bar-volume-indicator-font = 1


bar-volume-empty = ${bar.empty}
bar-volume-empty-font = 1
bar-volume-empty-foreground = ${colors.foreground}
bar-volume-fill = ${bar.fill}
bar-volume-fill-font = 1 
bar-volume-fill-foreground = ${colors.purple}


; ---------------------------------------------------------------------
;
[module/cpu_bar]
type = internal/cpu 
interval = 1
format-foreground = ${colors.purple}
format-padding = 1
label = %percentage:0.5%%
format = %{A1:plasma-systemmonitor &:}<label>%{A}

[module/cpu_icon]
type = custom/text
content = 󰘚
content-font = 1 
content-foreground = ${colors.lightpurple}
content-background = ${colors.background}
content-padding = 0.7
;---------------------------------------------
;

[module/cpu_temperature]
type = custom/script
interval = 1
exec = sensors | grep "Package id 0:" | tr -d '+' | awk '{print $4}'
label-padding = 1
label = %output%
label-foreground = ${colors.purple}
label-background = ${colors.background}
label-font = 1

[module/cpu_temperature_icon]
type = custom/text
content = 
content-font = 1
content-foreground = ${colors.lightpurple}
content-background = ${colors.background}
content-padding = 0.7
;---------------------------------------------
;


[module/memory]
type = internal/memory
interval = 1 
format-foreground = ${colors.purple}
format-padding = 1 
label = %used%
format = %{A1:plasma-systemmonitor &:}<label>%{A}

[module/memory_icon]
type = custom/text
content = 󰍛
content-foreground = ${colors.lightpurple} 
content-background = ${colors.background} 
content-padding = 0.7 
;---------------------------------------------


[module/xworkspaces]
type = internal/i3
pin-workspaces = false 
enable-click = true 
enable-scroll = true

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;󰽯
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-default = 󰖯

format = <label-state> <label-mode> 

label-mode = %mode%
label-mode-padding = 2
label-mode-background = ${colors.background}

label-focused =%index% %icon%
label-focused-foreground = ${colors.comment}
label-focused-background = ${colors.foreground}
label-focused-underline = ${colors.red}
label-focused-padding = 1 
label-focused-font = 8

label-unfocused = %index% %icon%
label-unfocused-padding = 1

;---------------------------------------------
[module/cat]
type = custom/text
content = "󰄛"
content-font = 2
content-padding = 0.5 
content-foreground = ${colors.purple} 
content-background = ${colors.background} 
;---------------------------------------------

;---------------------------------------------
;
[module/date]
type = internal/date
date = %d/%m
date-alt = %A, %d %B %Y
label = "%date%"
label-foreground = ${colors.purple}
label-background = ${colors.background}
label-padding = 1

[module/date_icon]
type = custom/text
content = 
content-font = 1 
content-foreground = ${colors.lightpurple} 
content-background = ${colors.background} 
content-padding = 0.7 
;---------------------------------------------
;
;---------------------------------------------
;
[module/time]
type = internal/date 
interval = 1 
time = %H:%M:%S 
label = "%time%"
label-foreground = ${colors.purple}
label-background = ${colors.background} 
label-padding = 1 

[module/time_icon]
type = custom/text 
content = 
content-font = 1 
content-foreground = ${colors.lightpurple} 
content-background = ${colors.background} 
content-padding = 0.7 
;---------------------------------------------
;

[module/mpd]
type = internal/mpd


interval = 1 
icon-play = 󰐌
icon-pause = 󰏥
icon-stop = 
icon-prev = 󰙣
icon-next = 󰙡
icon-random = 
icon-repeat = 󰕇

icon-play-foreground = ${colors.foreground}
icon-pause-foreground = ${colors.foreground}
icon-stop-foreground = ${colors.foreground}
icon-prev-foreground = ${colors.foreground}
icon-next-foreground = ${colors.foreground}
icon-random-foreground = ${colors.foreground}
icon-repeat-foreground = ${colors.foreground}


icon-play-font = 6 
icon-pause-font = 6 
icon-stop-font = 6
icon-prev-font = 6 
icon-next-font = 6 
icon-random-font = 6 

format-online = <icon-prev> <toggle> <icon-next> <icon-random>  <bar-progress> <label-time> <label-song>
format-online-padding = 1 
format-online-background = ${colors.background} 
format-online-foreground = ${colors.purple}
format-online-font = 9

label-song =%title%
label-song-maxlen = 20

label-offline = "MPD Offline"
bar-progress-width = 10
bar-progress-indicator = |
bar-progress-fill = ─
bar-progress-empty = ─

toggle-on-foreground = ${colors.foreground}
toggle-off-foreground = ${colors.foreground}
;---------------------------------------------
;
[module/sysmenu]
type = custom/text

content = 
content-foreground = ${color.foreground}
content-background = ${colors.background}
content-padding = 0.7
content-font = 6

click-left = ~/.config/rofi/powermenu/type-1/powermenu.sh &


;---------------------------------------------
[module/wired-network]
type = internal/network
interface-type = wired
interval = 1.0
label-connected-padding = 1
label-disconnected-padding = 1
format-connected = %{A:nm-connection-editor&:}<label-connected>%{A}
format-disconnected = %{A:nm-connection-editor&:}<label-disconnected>%{A}
label-connected = "󰍹 "
label-disconnected = "󰶐 "
label-connected-font = 1
label-disconnected-font = 1
label-connected-foreground = ${colors.lightpurple}
label-disconnected-foreground = ${colors.lightpurple}
format-connected-background = ${colors.background}
format-disconnected-background = ${colors.background}


[module/wireless-network]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 1.0

format-connected-padding = 0
format-disconnected-padding = 0
format-connected = %{A:nm-connection-editor&:}<ramp-signal><label-connected> %{A}
format-disconnected = %{A:nm-connection-editor&:}<label-disconnected>%{A}
label-connected = "%essid% "
label-disconnected = "󰤭 "
label-connected-font = 1
label-disconnected-font = 1

format-connected-background = ${colors.background}
format-disconnected-background = ${colors.background}
format-connected-foreground = ${colors.foreground}
format-disconnected-foreground = ${colors.foreground}

ramp-signal-0 = "󰤯 "
ramp-signal-1 = "󰤟 "
ramp-signal-2 = "󰤢 "
ramp-signal-3 = "󰤥 "
ramp-signal-4 = "󰤨 "



;----------------------------------------------
[module/filesystem]
type = internal/fs

; Mountpoints to display
mount-0 = /

; Seconds to sleep between updates
; Default: 30
interval = 10

; Display fixed precision values
; Default: false
fixed-values = true

; Spacing (number of spaces, pixels, points) between entries
; Default: 2
spacing = 4

; Default: 90
; New in version 3.6.0
warn-percentage = 75

format-mounted = <label-mounted>
format-unmounted = <label-unmounted>
label-mounted = %free%/%total%
label-mounted-background = ${colors.background}
label-mounted-foreground = ${colors.purple}

[module/filesystem_icon]
type = custom/text
content = 󰋊
content-font = 1 
content-foreground = ${colors.lightpurple} 
content-background = ${colors.background} 
content-padding = 0.7 

;---------------------------------------------
[module/sep]
type = custom/text
content = " "
content-padding = 0
content-foreground = ${colors.background}

