[colors]
background = #2e2557
foreground = #c8d3f5
pbackground = #6755ce
mbackground = #493c92
accent = #7b39ff
disabled = #444a73
color0 = #1b1d2b
color1 = #ff757f
color2 = #c3e88d
color3 = #ffc777
color4 = #a7a7ff
color5 = #c099ff
color6 = #86e1fc
color7 = #828bb8
color8 = #c8d3f5
color9 = #caa4ff
white = #fff
alert = #ff757f


[bar/main]
width = 100%
height = 24px
radius = 0

fixed-center = true

offset-x = 0
offset-y = 0

background = ${colors.background}
foreground = ${colors.foreground}


border-size = 6px
border-color = ${colors.background}

padding-left = 5pt
padding-right = 5pt

module-margin = 0px

line-size = 2pt

font-0 = CaskaydiaCoveNerdFont-Regular:size=10;2
font-1 = CaskaydiaCoveNerdFontMono-Regular:size=26;6
font-2 = CaskaydiaCoveNerdFontMono-Regular:size=12;2
font-3 = CaskaydiaCoveNerdFontMono-Regular:antialias=false:size=22;5.1
font-4 = CaskaydiaCoveNerdFontMono-Regular:size=18;4
font-5 = CaskaydiaCoveNerdFont-Regular:size=14;3
font-6 = CaskaydiaCoveNerdFont-Regular:size=8;1.5
modules-left = powerlineLA2 cat powerlineRA2 xworkspaces powerlineR sep powerlineL memory cpu cputemperature powerlineR
modules-center = powerlineL date time powerlineR
modules-right = powerlineL music sep wired-network wireless-network powerlineLA shutdown powerlineRA 

cursor-click = pointer
;enable-ipc = true

[module/xworkspaces]
type = internal/xworkspaces


label-active = %{T6}%name%%{T-}
label-active-foreground =  #cba9ff
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1
label-occupied-foreground = ${colors.white}

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.color7}
label-empty-padding = 1

label-occupied-background = ${colors.mbackground}
label-empty-background = ${colors.mbackground}
label-active-background = ${colors.mbackground}

reverse-scroll = true



[module/memory]
type = internal/memory
interval = 1
format-foreground = ${colors.color6}
format-padding = 1
format-background = ${colors.mbackground}
label = 󰑭 %used%
format = %{A1:plasma-systemmonitor &:}<label>%{A}


[module/cpu]
type = internal/cpu
interval = 1
format-foreground = ${colors.color6}
format-padding = 1
format-background = ${colors.mbackground}
label =  %percentage:0.5%%
format = %{A1:plasma-systemmonitor &:}<label>%{A}

[module/cputemperature]
type = custom/script
interval = 1
exec = sensors | grep "Package id 0:" | tr -d '+' | awk '{print $4}'
label-padding = 1
label =  %output%
label-foreground = ${colors.color3}
label-background = ${colors.mbackground}



[module/time]
type = internal/date
interval = 1
time = 󰥔 %I:%M %p
label =  "%time%"
label-foreground = ${colors.color8}
label-background = ${colors.mbackground}
label-padding = 1


[module/date]
type = internal/date
date = 󰃭 %d/%m
date-alt = %A, %d %B %Y
label = "%date%"
label-foreground = ${colors.color8}
label-background = ${colors.mbackground}
label-padding = 1


[module/cat]
type = custom/text
content = "󰄛"
content-font = 2
content-padding = 0.5
content-background = ${colors.pbackground}
click-left = krunner &


[module/shutdown]
type = custom/text
content = ""
content-font = 5
content-padding = 0
content-foreground = ${colors.color1}
content-background = ${colors.pbackground}
click-left = qdbus org.kde.ksmserver /KSMServer logout 1 2 3



[module/wired-network]
type = internal/network
interface-type = wired
interval = 1.0
label-connected-padding = 1
label-disconnected-padding = 1
format-connected = %{A:nm-connection-editor&:}<label-connected>%{A}
format-disconnected = %{A:nm-connection-editor&:}<label-disconnected>%{A}
label-connected = "󰈀 "
label-disconnected = "󰈀 "
label-connected-font = 1
label-disconnected-font = 1
label-connected-foreground = ${colors.color8}
label-disconnected-foreground = ${colors.color1}
format-connected-background = ${colors.mbackground}
format-disconnected-background = ${colors.mbackground}


[module/wireless-network]
type = internal/network
interface = wlan0
interface-type = wireless
interval = 1.0

format-connected-padding = 0
format-disconnected-padding = 0
format-connected = %{A:nm-connection-editor&:}<ramp-signal><label-connected> %{A}
format-disconnected = %{A:nm-connection-editor&:}<label-disconnected>%{A}
label-connected = "%essid% "
label-disconnected = "󰤭 "
label-connected-font = 1
label-disconnected-font = 1

format-connected-background = ${colors.mbackground}
format-disconnected-background = ${colors.mbackground}
format-connected-foreground = ${colors.color6}
format-disconnected-foreground = ${colors.color1}

ramp-signal-0 = "󰤯 "
ramp-signal-1 = "󰤟 "
ramp-signal-2 = "󰤢 "
ramp-signal-3 = "󰤥 "
ramp-signal-4 = "󰤨 "


[module/systray]
type = custom/text
content = " "
content-font = 3
content-padding = 0
content-foreground = ${colors.color8}
content-background = ${colors.mbackground}
click-left = xdotool keydown Super+ctrl+F1 && xdotool keyup Super+ctrl+F1


[module/music]
type = internal/mpd

; Host where mpd is running (either ip or domain name)
; Can also be the full path to a unix socket where mpd is running.
;;host = 127.0.0.1
;;port = 6600
;;password = mysecretpassword

; Seconds to sleep between progressbar/song timer sync
; Default: 1
interval = 1

; Available tags:
;   <label-song> (default)
;   <label-time>
;   <bar-progress>
;   <toggle> - gets replaced with <icon-(pause|play)>
;   <toggle-stop> - gets replaced with <icon-(stop|play)>
;   <icon-random>
;   <icon-repeat>
;   <icon-repeatone> (deprecated)
;   <icon-single> - Toggle playing only a single song. Replaces <icon-repeatone>
;   <icon-consume>
;   <icon-prev>
;   <icon-stop>
;   <icon-play>
;   <icon-pause>
;   <icon-next>
;   <icon-seekb>
;   <icon-seekf>
format-online = <label-song> <icon-prev> <toggle> <icon-next> <icon-repeat>
format-online-prefix = 
format-online-prefix-foreground = ${color.1}

;format-playing = ${self.format-online}
;format-paused = ${self.format-online}
;format-stopped = ${self.format-online}

; Available tags:
;   <label-offline>
format-offline = <label-offline>
format-offline-prefix = 
format-offline-prefix-foreground = ${color.1}

; Available tokens:
;   %artist%
;   %album-artist%
;   %album%
;   %date%
;   %title%
; Default: %artist% - %title%
label-song =  " %artist% - %title%"
label-song-maxlen = 25
label-song-ellipsis = true

; Available tokens:
;   %elapsed%
;   %total%
; Default: %elapsed% / %total%
label-time = %elapsed% / %total%
label-time-background = ${color.1}
label-time-padding = 1

; Available tokens:
;   None
label-offline = " Offline"

; Only applies if <icon-X> is used
icon-play = 󰐍
icon-play-foreground = ${color.1}
icon-pause = 󰏦
icon-pause-foreground = ${color.1}
icon-stop = 
icon-stop-foreground = ${color.1}
icon-next = 󰙢
icon-next-foreground = ${color.1}
icon-prev = 󰙤
icon-prev-foreground = ${color.1}
icon-seekf = 
icon-seekb = 
icon-random = 
icon-repeat = 󰑖
icon-repeatone = 
icon-single = 
icon-consume =

; Used to display the state of random/repeat/repeatone/single
; Only applies if <icon-[random|repeat|repeatone|single]> is used
toggle-on-foreground = ${color.1}
toggle-off-foreground = ${color.1}

; Only applies if <bar-progress> is used
;;bar-progress-width = 45
;;bar-progress-indicator = |
;;bar-progress-fill = ─
;;bar-progress-empty = ─

[module/powerlineRA]
type = custom/text
content = ""
content-font = 4
content-padding = 0
content-foreground = ${colors.pbackground}



[module/powerlineLA]
type = custom/text
content = ""
content-font = 4
content-padding = 0
content-background = ${colors.mbackground}
content-foreground = ${colors.pbackground}

[module/powerlineRA2]
type = custom/text
content = ""
content-font = 4
content-padding = 0
content-background = ${colors.mbackground}
content-foreground = ${colors.pbackground}


[module/powerlineLA2]
type = custom/text
content = ""
content-font = 4
content-padding = 0

content-foreground = ${colors.pbackground}



[module/powerlineR]
type = custom/text
content = ""
content-font = 4
content-padding = 0
content-foreground = ${colors.mbackground}


[module/powerlineL]
type = custom/text
content = ""
content-font = 4
content-padding = 0
content-foreground = ${colors.mbackground}

[module/sep]
type = custom/text
content = " "
content-font = 1
content-padding = 0
content-foreground = ${colors.background}



[settings]
screenchange-reload = false
pseudo-transparency = false
